name: Installation Problem
description: Report installation or environment issues
title: "[INSTALL] "
labels: ["bug", "installation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an installation issue! Please provide the following information to help us diagnose the problem.

  - type: input
    id: version
    attributes:
      label: QuietPatch Version
      description: Run `quietpatch --version` and paste the output
      placeholder: "quietpatch --version"
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: Run `python --version` and paste the output
      placeholder: "python --version"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What operating system are you using?
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows 10
        - Windows 11
        - Ubuntu 22.04
        - Ubuntu 24.04
        - Other Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: doctor_output
    attributes:
      label: Environment Diagnosis
      description: Run `quietpatch env doctor` and paste the complete output
      placeholder: "quietpatch env doctor"
    validations:
      required: true

  - type: dropdown
    id: offline_mode
    attributes:
      label: Offline Mode
      description: Is QP_OFFLINE=1 set in your environment?
      options:
        - No (online mode)
        - Yes (offline mode)
        - Not sure
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: Error Message
      description: What error message did you see? Include the full traceback if available.
      placeholder: "Paste the complete error message here"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: What did you do to trigger this issue?
      placeholder: |
        1. Installed QuietPatch using...
        2. Ran command...
        3. Got error...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: "Describe what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: "Add any other context about the problem here"
