# QuietPatch policy (optional). Leave sections empty to disable.
allow:            []   # e.g., ["apple:safari", "microsoft:word"] or ["Safari"] (app name)
deny:             []   # e.g., ["games:*", "raycast:*"] or ["Hidden Folks"] (app name)
min_severity:     low   # one of: none, low, medium, high, critical
treat_unknown_as: low   # how to treat apps with unknown severity
only_with_cves:   true     # hide apps that have zero CVEs
# Optional: cap output size
limit_per_app:    50      # keep top-N CVEs per app (by risk)
