name: ci

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          python -m pip install ruff
          ruff check .

  unit:
    name: unit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -e . pytest
          pytest -q

  build-linux:
    name: build-linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip wheel setuptools pex
          python -m pip install -e .
          mkdir -p dist
          python -m pex quietpatch -c quietpatch \
            -o dist/quietpatch-linux-x86_64-py311.pex \
            --validate-entry-point --no-build --venv prepend --strip-pex-env
      - name: smoke
        run: |
          python3.11 dist/quietpatch-linux-x86_64-py311.pex scan --help >/dev/null
