name: ci
on:
  pull_request:
  push:
    branches: [ main, ci-fix ]
  workflow_dispatch:

env:
  PY_VER: "3.11"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
          cache: "pip"
      - name: Install ruff (pinned) with retry
        run: |
          set -eux
          python -m pip install -r requirements.ci.txt
          python -m ruff --version
      - name: Run ruff
        run: |
          ruff check . --fix || true
          ruff format . || true
        env:
          # keep lint fast/sane
          RUFF_CACHE_DIR: .ruff_cache

  unit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
          cache: "pip"
      - name: Install project + test deps
        run: |
          set -eux
          python -m pip install -r requirements.ci.txt
          python -m pip install -e .
      - name: Run tests
        run: pytest -q

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
          cache: "pip"
      - name: Build wheel
        run: |
          python -m pip install -U pip build wheel setuptools
          python -m build -w -n
          ls -l dist/*.whl
      - name: Build PEX from local wheel (deps from PyPI)
        run: |
          python -m pip install -U pex
          mkdir -p dist-pex
          python -m pex dist/*.whl \
            -c quietpatch \
            --find-links dist \
            --validate-entry-point --no-build \
            --venv prepend --strip-pex-env \
            -o dist-pex/quietpatch-linux-x86_64-py311.pex
      - name: Smoke
        env:
          PEX_ROOT: ${{ github.workspace }}/.pexroot
          TMP: ${{ github.workspace }}/.tmp
          TEMP: ${{ github.workspace }}/.tmp
        run: |
          python3.11 dist-pex/quietpatch-linux-x86_64-py311.pex scan --help >/dev/null
      - uses: actions/upload-artifact@v4
        with:
          name: quietpatch-linux
          path: dist-pex/*

  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", architecture: "x64", cache: "pip" }

      - name: Build wheel
        shell: pwsh
        run: |
          py -3.11 -m pip install -U pip build wheel setuptools
          py -3.11 -m build -w -n
          Get-ChildItem dist\*.whl | Format-List

      - name: Build PEX from local wheel (deps from PyPI)
        shell: pwsh
        env:
          PEX_IGNORE_RCFILES: '1'
        run: |
          py -3.11 -m pip install pex==2.54.2
          New-Item -ItemType Directory -Force -Path dist-pex | Out-Null
          $whl = (Get-ChildItem dist\*.whl | Select-Object -First 1).FullName
          py -3.11 -m pex $whl `
            -c quietpatch `
            --find-links dist `
            --no-build `
            --strip-pex-env `
            -o dist-pex\quietpatch-win-py311.pex

      - name: Smoke
        shell: pwsh
        env:
          # SINGLE-QUOTED to avoid YAML escape sequences
          PEX_ROOT: 'C:\pex'
          TMP: 'C:\t'
          TEMP: 'C:\t'
          PEX_IGNORE_RCFILES: '1'
        run: |
          py -3.11 dist-pex\quietpatch-win-py311.pex scan --help >$null

      - uses: actions/upload-artifact@v4
        with: { name: quietpatch-windows, path: dist-pex/* }

  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
          cache: "pip"
      - name: Build wheel
        run: |
          python -m pip install -U pip build wheel setuptools
          python -m build -w -n
          ls -l dist/*.whl
      - name: Build PEX from local wheel (deps from PyPI)
        run: |
          python -m pip install -U pex
          mkdir -p dist-pex
          python -m pex dist/*.whl \
            -c quietpatch \
            --find-links dist \
            --validate-entry-point --no-build \
            --venv prepend --strip-pex-env \
            -o dist-pex/quietpatch-macos-arm64-py311.pex
      - name: Smoke
        run: |
          python3.11 dist-pex/quietpatch-macos-arm64-py311.pex scan --help >/dev/null
      - uses: actions/upload-artifact@v4
        with:
          name: quietpatch-macos
          path: dist-pex/*

  smoke-install:
    name: smoke-install
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    env:
      OWNER: ${{ github.repository_owner }}
      REPO:  ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            os: linux
          - runner: macos-14
            os: macos
          - runner: windows-latest
            os: windows
    steps:
      - name: Add local bin to PATH
        if: matrix.os != 'windows'
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Smoke install via API (curl)
        if: matrix.os != 'windows'
        run: |
          set -euo pipefail
          curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh | bash
          command -v quietpatch >/dev/null || { echo "quietpatch not on PATH"; exit 86; }
          quietpatch --version

      - name: Add local bin to PATH (Windows)
        if: matrix.os == 'windows'
        shell: pwsh
        run: |
          echo "$env:USERPROFILE\.quietpatch\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding ascii -Append

      - name: Smoke install via API (irm)
        if: matrix.os == 'windows'
        shell: pwsh
        run: |
          $env:OWNER='${{ github.repository_owner }}'
          $env:REPO='${{ github.event.repository.name }}'
          $env:GITHUB_TOKEN='${{ secrets.GITHUB_TOKEN }}'
          irm https://raw.githubusercontent.com/${{ github.repository }}/main/install.ps1 | iex
          if (-not (Get-Command quietpatch -ErrorAction SilentlyContinue)) { Write-Error "quietpatch not on PATH"; exit 86 }
          quietpatch --version