name: installer-smoke
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Smoke install via curl
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          curl -fsSL "https://raw.githubusercontent.com/${{ github.repository }}/$GITHUB_SHA/install.sh" | /bin/bash
          export PATH="$HOME/.local/bin:$PATH"
          quietpatch --version | cat

  windows:
    runs-on: windows-latest
    steps:
      - name: Smoke install via irm
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $ErrorActionPreference = 'Stop'
          irm "https://raw.githubusercontent.com/${{ github.repository }}/$env:GITHUB_SHA/install.ps1" | iex
          quietpatch --version | Out-Host
