name: PR Checks

on:
  pull_request:
    branches: [ main, master, Quietpatch-update ]
  push:
    branches: [ main, master, Quietpatch-update ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            requirements.ci.txt
            requirements-ci.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.ci.txt -r requirements-ci.txt
          pip install -e .

      - name: Run tests
        run: pytest -q
