name: PR Checks

on:
  pull_request:
    branches: [ main, master, Quietpatch-update ]
  push:
    branches: [ main, master, Quietpatch-update ]

jobs:
  test:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            requirements.ci.txt
            requirements-ci.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.ci.txt -r requirements-ci.txt
          pip install -e .

      - name: Run tests
        run: pytest -q

      - name: Zero-unknowns gate (mock, offline, capped)
        shell: bash
        run: |
          set -euo pipefail

          workdir="$(mktemp -d)"
          sarif="$workdir/gate.sarif"

          echo "Running quietpatch scan (mock) → SARIF only…"
          if ! timeout 90s quietpatch scan --mock --offline --fail-unknowns --sarif "$sarif"; then
            echo "::error::Scan failed or exceeded 90s. Failing fast."; exit 1
          fi

          if [ ! -s "$sarif" ]; then
            echo "::error::No SARIF produced by quietpatch"; exit 1
          fi

          echo "Zero-unknowns gate passed ✅"
