name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-ci.txt ]; then pip install -r requirements-ci.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install pytest PyYAML==6.0.2
      - name: Lint (basic)
        run: python -m py_compile $(git ls-files '*.py') || true
      - name: Tests
        run: pytest -q
