name: Python CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      - name: Lint (basic)
        run: python -m py_compile $(git ls-files '*.py') || true
      - name: Tests
        run: |
          if [ -d tests ]; then pytest -q; else echo "No tests directory"; fi
