name: python-ci

on:
  push:
    branches: ["**"]        # run on any branch
  pull_request:
    branches: ["**"]        # run on any PR
  workflow_dispatch:

jobs:
  sanity:
    name: sanity
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "CI wiring OK"
          echo "ref=$GITHUB_REF event=$GITHUB_EVENT_NAME"

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install -U pip ruff
          ruff check . --fix
          ruff format .

  unit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install -U pip
          python -m pip install -e . pytest
          pytest -q

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install -U pip wheel setuptools pex
          python -m pip install -e .
          mkdir -p dist
          python -m pex quietpatch -c quietpatch \
            -o dist/quietpatch-linux-x86_64-py311.pex \
            --validate-entry-point --no-build --venv prepend --strip-pex-env