name: python-ci

on:
  push:          # any branch
  pull_request:  # any PR
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI wiring OK: $GITHUB_REF $GITHUB_EVENT_NAME"