name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
    
    - name: Tests (with coverage gate)
      run: pytest -q --cov=src --cov-report=term-missing --cov-fail-under=70
=======
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-ci.txt ]; then pip install -r requirements-ci.txt; fi
          pip install pytest
      - name: Lint (basic)
        run: python -m py_compile $(git ls-files '*.py') || true
      - name: Tests
        run: |
          if [ -d tests ]; then pytest -q; else echo "No tests directory"; fi
>>>>>>> caf34a1 (CI: use minimal deps; guard GUI deps with markers)
