name: Regenerate Linux Constraints

on:
  workflow_dispatch:

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install pip-tools (pin)
        run: python -m pip install "pip-tools>=7.4.1,<8"
      
      - name: Regenerate Linux constraints
        run: |
          python -m piptools compile \
            --resolver=backtracking \
            --generate-hashes \
            -o constraints/runtime-linux-py312.txt \
            pyproject.toml
      
      - name: Verify SecretStorage and jeepney are included
        run: |
          grep -q '^SecretStorage==' constraints/runtime-linux-py312.txt || (echo "Missing SecretStorage pin"; exit 1)
          grep -q '^jeepney==' constraints/runtime-linux-py312.txt || (echo "Missing jeepney pin"; exit 1)
          echo "✅ Both SecretStorage and jeepney are properly pinned with hashes"
      
      - name: Show diff
        run: |
          echo "=== Generated constraints file ==="
          head -20 constraints/runtime-linux-py312.txt
          echo "..."
          tail -10 constraints/runtime-linux-py312.txt
      
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: regenerate linux constraints (py312, manylinux_2_28)"
          file_pattern: constraints/runtime-linux-py312.txt
