name: Regenerate Linux Constraints

on:
  workflow_dispatch:

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Pin packaging stack (pip <25 + pip-tools 7.4.x)
        run: |
          python -m pip install -U "pip<25" "setuptools>=68" wheel "pip-tools>=7.4.1,<7.5"
          python -m pip --version
          pip-compile --version
      
      - name: Regenerate constraints (Linux, py312)
        run: |
          python -m piptools compile -q --generate-hashes -o constraints/runtime-linux-py312.txt pyproject.toml

      - name: Force-pin Linux-only transitive deps (SecretStorage/jeepney)
        run: |
          set -e
          mkdir -p wheelhouse
          python -m pip download --only-binary=:all: -d wheelhouse "SecretStorage==3.4.0" "jeepney==0.8.0"
          py() {
            python - "$@" <<'PY'
import glob, hashlib, os, sys
out = []
for whl in sorted(glob.glob("wheelhouse/*.whl")):
    name = os.path.basename(whl).lower()
    h = hashlib.sha256(open(whl, "rb").read()).hexdigest()
    if name.startswith("secretstorage-"):
        out.append(f"SecretStorage==3.4.0 \\\n    --hash=sha256:{h}\n    # via keyring")
    if name.startswith("jeepney-"):
        out.append(f"jeepney==0.8.0 \\\n    --hash=sha256:{h}\n    # via keyring")
open("constraints/runtime-linux-py312.txt","a").write("\n" + "\n".join(out) + "\n")
PY
          }
          py
      
      - name: Show diff
        run: git --no-pager diff --color -- constraints/runtime-linux-py312.txt || true
      
      - name: Verify SecretStorage and jeepney are included
        run: |
          grep -q '^SecretStorage==' constraints/runtime-linux-py312.txt || (echo "Missing SecretStorage pin"; exit 1)
          grep -q '^jeepney==' constraints/runtime-linux-py312.txt || (echo "Missing jeepney pin"; exit 1)
          echo "✅ Both SecretStorage and jeepney are properly pinned with hashes"
      
      - name: Show diff
        run: |
          echo "=== Generated constraints file ==="
          head -20 constraints/runtime-linux-py312.txt
          echo "..."
          tail -10 constraints/runtime-linux-py312.txt
      
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: regenerate linux constraints (py312, manylinux_2_28)"
          file_pattern: constraints/runtime-linux-py312.txt
