name: release-guardrail
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  verify-assets:
    runs-on: ubuntu-22.04
    steps:
      - name: Check release assets present
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          REPO=matt-c-g/quietpatch
          API="https://api.github.com/repos/${REPO}/releases/latest"
          JSON=$(curl -fsSL -H "Authorization: Bearer ${GH_TOKEN}" "$API")
          has() { echo "$JSON" | jq -e --arg re "$1" '.assets[]|select(.name|test($re;"i"))' >/dev/null; }
          req() { has "$1" || { echo "Missing asset matching: $1" >&2; exit 1; }; }
          # required assets
          req '^quietpatch-macos.*(arm64).*\\.(zip|pex)$'
          req '^quietpatch-linux.*(x86_64|amd64).*\\.(zip|pex)$'
          req '^quietpatch-win.*\\.pex$|^quietpatch-windows.*\\.zip$'
          req '^SHA256SUMS$'
          echo "All required assets present."
