name: build-release-pex

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-14]
        py: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip wheel setuptools pex
          python -m pip install -e .

      - name: Build PEX
        shell: bash
        run: |
          mkdir -p dist
          case "${{ matrix.os }}" in
            windows-latest)
              python -m pex quietpatch -c quietpatch -o dist/quietpatch-win-py311.pex --validate-entry-point --no-build --venv prepend --strip-pex-env
              ;;
            ubuntu-latest)
              python -m pex quietpatch -c quietpatch -o dist/quietpatch-linux-py311.pex --validate-entry-point --no-build --venv prepend --strip-pex-env
              ;;
            macos-14)
              python -m pex quietpatch -c quietpatch -o dist/quietpatch-macos-arm64-py311.pex --validate-entry-point --no-build --venv prepend --strip-pex-env
              ;;
          esac

      - name: Attach wrapper (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cat > dist/run_quietpatch.bat <<'BAT'
          @echo off
          setlocal
          set PEX_ROOT=%~dp0.pexroot
          set TMP=%~dp0.tmp
          set TEMP=%~dp0.tmp
          where py >nul 2>&1
          if %ERRORLEVEL% neq 0 (
            echo Python launcher not found. Please install Python 3.11 (64-bit) and retry.
            exit /b 86
          )
          py -3.11 "%~dp0quietpatch-win-py311.pex" %*
          endlocal
          BAT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pex-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: pex-*
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            pex-windows-latest/quietpatch-win-py311.pex
            pex-windows-latest/run_quietpatch.bat
            pex-ubuntu-latest/quietpatch-linux-py311.pex
            pex-macos-14/quietpatch-macos-arm64-py311.pex

