name: release-gates
on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  gates:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install minimal deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest -q tests
          
      - name: Build offline DB fixture if missing
        run: |
          mkdir -p data/db

      - name: Test database refresh from local feed
        run: |
          python3 tools/make_manifest.py --src data/db --out _feed --version "test-$(date +%F)" --gzip
          python3 qp_cli.py db refresh --mirror "file://$PWD/_feed"
          test -f data/db/manifest.json

      - name: Selfcheck (strict)
        env:
          QP_OFFLINE: "1"
          QP_DISABLE_AUTO_SYNC: "1"
        run: |
          python tools/selfcheck.py --strict

      - name: Coverage gate
        run: |
          set -e
          if [ ! -f data/vuln_log.json ]; then
            echo "Creating minimal test vuln_log.json for gates"
            mkdir -p data
            echo '[{"name": "test-app", "vulnerabilities": [{"cve_id": "CVE-2023-1234"}]}]' > data/vuln_log.json
          fi
          python3 tools/check_coverage.py