name: release

on:
  push:
    tags: ["v*.*.*"]   # tag like v0.3.1
  workflow_dispatch:

env:
  PY_VER: "3.11"

jobs:
  win:
    name: build-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
          architecture: "x64"
      - shell: pwsh
        run: |
          python -m pip install -U pip wheel setuptools pex
          python -m pip install -e .
          mkdir dist
          python -m pex -D . -r requirements.pex.txt `
            --interpreter-constraint 'CPython>=3.11,<3.14' `
            -m qp_cli:main `
            -o dist/quietpatch-win-py311.pex
      - name: Package (wrapper + README)
        shell: pwsh
        run: |
          Set-Content -NoNewline -Path dist\run_quietpatch.bat -Value '@echo off
          setlocal
          set PEX_ROOT=%~dp0.pexroot
          set TMP=%~dp0.tmp
          set TEMP=%~dp0.tmp
          where py >nul 2>&1 || (echo Install Python 3.11 (64-bit) and retry.& exit /b 86)
          py -3.11 "%~dp0quietpatch-win-py311.pex" %*
          endlocal'
          Set-Content -Path dist\README-Windows.txt -Value 'QuietPatch (Windows)
          Requirements: Python 3.11 (64-bit)
          Run: double-click run_quietpatch.bat
          Report: .\reports\quietpatch_report.html'
          if (Test-Path catalog) { Copy-Item -Recurse catalog dist/catalog }
          if (Test-Path policies) { Copy-Item -Recurse policies dist/policies }
      - name: Zip
        shell: bash
        run: |
          ver="${GITHUB_REF_NAME#v}"
          mkdir -p release
          (cd dist && zip -r9 "../release/quietpatch-${ver}-windows.zip" .)
      - uses: actions/upload-artifact@v4
        with:
          name: win-zip
          path: release/*.zip

  linux:
    name: build-linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
      - run: |
          python -m pip install -U pip wheel setuptools pex
          python -m pip install -e .
          mkdir -p dist
          python -m pex -D . -r requirements.pex.txt \
            --interpreter-constraint 'CPython>=3.11,<3.14' \
            -m qp_cli:main \
            -o dist/quietpatch-linux-x86_64-py311.pex
          cat > dist/run_quietpatch.sh <<'SH'
          #!/usr/bin/env bash
          set -euo pipefail
          export PEX_ROOT="$(dirname "$0")/.pexroot"
          exec /usr/bin/env python3.11 "$(dirname "$0")/quietpatch-linux-x86_64-py311.pex" "$@"
          SH
          chmod +x dist/run_quietpatch.sh
          printf '%s\n' \
            'QuietPatch (Linux)' \
            'Requirements: Python 3.11.' \
            'Run:' \
            '  chmod +x run_quietpatch.sh' \
            '  ./run_quietpatch.sh scan' \
            'Report: ./reports/quietpatch_report.html' > dist/README-Linux.txt
          if [ -d catalog ]; then cp -r catalog dist/catalog; fi
          if [ -d policies ]; then cp -r policies dist/policies; fi
      - name: Zip
        run: |
          ver="${GITHUB_REF_NAME#v}"
          mkdir -p release
          (cd dist && zip -r9 "../release/quietpatch-${ver}-linux-x86_64.zip" .)
      - uses: actions/upload-artifact@v4
        with:
          name: linux-zip
          path: release/*.zip

  macos:
    name: build-macos
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
      - run: |
          python -m pip install -U pip wheel setuptools pex
          python -m pip install -e .
          mkdir -p dist
          python -m pex -D . -r requirements.pex.txt \
            --interpreter-constraint 'CPython>=3.11,<3.14' \
            -m qp_cli:main \
            -o dist/quietpatch-macos-arm64-py311.pex
          cat > dist/run_quietpatch.command <<'SH'
          #!/usr/bin/env bash
          set -euo pipefail
          export PEX_ROOT="$(dirname "$0")/.pexroot"
          exec /usr/bin/env python3.11 "$(dirname "$0")/quietpatch-macos-arm64-py311.pex" "$@"
          SH
          chmod +x dist/run_quietpatch.command
          printf '%s\n' \
            'QuietPatch (macOS, Apple Silicon)' \
            'Requirements: Python 3.11 (brew install python@3.11).' \
            'Run: double-click run_quietpatch.command' \
            'Report: ./reports/quietpatch_report.html' > dist/README-macOS.txt
          if [ -d catalog ]; then cp -r catalog dist/catalog; fi
          if [ -d policies ]; then cp -r policies dist/policies; fi
      - name: Zip
        run: |
          ver="${GITHUB_REF_NAME#v}"
          mkdir -p release
          (cd dist && zip -r9 "../release/quietpatch-${ver}-macos-arm64.zip" .)
      - uses: actions/upload-artifact@v4
        with:
          name: mac-zip
          path: release/*.zip

  publish:
    name: publish
    needs: [win, linux, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { pattern: "*-zip", merge-multiple: true }
      - name: Checksums
        run: |
          ls -l
          sha256sum *.zip > SHA256SUMS
      - name: Minisign sign (optional but recommended)
        if: ${{ secrets.MINISIGN_SECRET_KEY != '' }}
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}
        run: |
          echo "$MINISIGN_SECRET_KEY" > key.txt
          docker run --rm -v "$PWD:/w" -w /w ghcr.io/jedisct1/minisign minisign -S -s key.txt -m SHA256SUMS
          rm -f key.txt
      - name: Create VERIFY.md
        run: |
          cat > VERIFY.md << 'EOF'
          # Verify QuietPatch release
          
          ## 1) Verify checksums
          - **Linux/macOS**
            ```sh
            sha256sum -c SHA256SUMS
            ```
          - **Windows (PowerShell)**
            ```powershell
            Get-Content .\SHA256SUMS
            # For a single file:
            Get-FileHash .\quietpatch-<ver>-windows.zip -Algorithm SHA256
            ```
          
          ## 2) Verify signature (if provided)
          Install minisign:
          - **macOS**: `brew install minisign`
          - **Linux**: `sudo apt install minisign` or equivalent
          - **Windows**: Download `minisign.exe`
          
          Verify:
          ```sh
          minisign -Vm SHA256SUMS -P <YOUR_PUBLIC_KEY>
          ```
          
          **If checksum or signature fails: do not run the binaries—re-download from the Release page.**
          EOF
      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
            SHA256SUMS
            SHA256SUMS.minisig
            VERIFY.md

