name: Release
on:
  workflow_dispatch:
  push:
    tags: [ 'v*' ]

jobs:
  mac-pkg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build zipapp
        run: |
          python3 -m pip install -r requirements-ci.txt
          bash tools/build_pyz.sh  # <- your existing builder
          mkdir -p packaging/macos/payload/usr/local/quietpatch
          cp dist/quietpatch.pyz packaging/macos/payload/usr/local/quietpatch/quietpatch.pyz
      - name: Build pkg
        run: packaging/macos/mkpkg.sh ${GITHUB_REF_NAME#v}
      - name: Sign (optional)
        if: env.INSTALLER_ID != ''
        run: |
          productsign --sign "${{ env.INSTALLER_ID }}" packaging/macos/quietpatch-${GITHUB_REF_NAME#v}.pkg \
            packaging/macos/quietpatch-${GITHUB_REF_NAME#v}-signed.pkg
      - name: Notarize (optional)
        if: env.NOTARY_PROFILE != ''
        run: |
          xcrun notarytool submit packaging/macos/quietpatch-${GITHUB_REF_NAME#v}-signed.pkg \
            --keychain-profile "${{ env.NOTARY_PROFILE }}" --wait
          xcrun stapler staple packaging/macos/quietpatch-${GITHUB_REF_NAME#v}-signed.pkg
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quietpatch-macos-pkg
          path: packaging/macos/*.pkg

